In [10]:
import pandas as pd
import numpy as np

In [42]:
data_main = pd.read_csv('./data/AA06LC00_Nback_2021_Jun_09_1034.csv')
data_ref  = pd.read_csv('./data/nback_AB.csv')

In [12]:
data_main.describe()

,Unnamed: 0,subj_key_resp_first,rxn_time,corr_resp,corr_resp_left,running_time,hits,corr_skips,false_alarm,misses,total_hits,total_corr_skips,total_false_alarm,total_misses,overall_accuracy,hit_accuracy,false_alarm_rate,avg_rxn_time
count,198.000000,46.0,46.000000,180.000000,180.000000,18.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,198.000000,197.000000,196.000000,197.000000,196.000000
mean,98.500000,1.0,1.299291,0.300000,2.100000,421.667415,0.222222,0.626263,0.010101,0.050505,23.373737,61.348485,1.787879,3.489899,94.388616,90.170620,2.686895,2.009594
std,57.301832,0.0,2.656948,0.459536,3.216751,268.371063,0.416794,0.485022,0.100248,0.219540,12.577545,36.171823,0.519131,3.327687,1.834909,6.131742,1.869203,0.809873
min,0.000000,1.0,0.375787,0.000000,0.000000,0.207622,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,90.000000,79.591837,0.000000,0.448161
25%,49.250000,1.0,0.473066,0.000000,0.000000,205.085767,0.000000,0.000000,0.000000,0.000000,13.000000,29.250000,2.000000,1.000000,93.220339,85.274390,1.398601,1.439926
50%,98.500000,1.0,0.556506,0.000000,0.000000,421.895466,0.000000,1.000000,0.000000,0.000000,25.000000,61.000000,2.000000,2.000000,94.308943,91.304348,2.020202,1.664216
75%,147.750000,1.0,0.670108,1.000000,7.000000,638.698934,0.000000,1.000000,0.000000,0.000000,34.000000,92.750000,2.000000,6.000000,95.402299,93.598790,3.571429,2.523675
max,197.000000,1.0,14.287744,1.000000,7.000000,843.620533,1.000000,1.000000,1.000000,1.000000,44.000000,124.000000,2.000000,10.000000,100.000000,100.000000,10.000000,3.909825

In [5]:
data_main

,Unnamed: 0,subj_key_resp,subj_key_resp_first,rxn_time,corr_resp,corr_resp_left,running_time,hits,corr_skips,false_alarm,misses,total_hits,total_corr_skips,total_false_alarm,total_misses,overall_accuracy,hit_accuracy,false_alarm_rate,avg_rxn_time
0,0,NaN,NaN,NaN,NaN,NaN,0.207622,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,0,1,0,0,100.000000,NaN,0.000000,NaN
2,2,"[('1', 0.47146260004956275)]",1.0,0.471463,1.0,7.0,NaN,1,0,0,0,1,1,0,0,100.000000,100.000000,0.000000,0.471463
3,3,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,1,2,0,0,100.000000,100.000000,0.000000,0.471463
4,4,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,1,3,0,0,100.000000,100.000000,0.000000,0.471463
5,5,"[('1', 0.42485980002675205)]",1.0,0.424860,1.0,7.0,NaN,1,0,0,0,2,3,0,0,100.000000,100.000000,0.000000,0.448161
6,6,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,2,4,0,0,100.000000,100.000000,0.000000,0.448161
7,7,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,2,5,0,0,100.000000,100.000000,0.000000,0.448161
8,8,"[('1', 0.4552331999875605)]",1.0,0.455233,1.0,7.0,NaN,1,0,0,0,3,5,0,0,100.000000,100.000000,0.000000,0.450519
9,9,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,3,6,0,0,100.000000,100.000000,0.000000,0.450519
10,10,"[('1', 14.287743899971247)]",1.0,14.287744,0.0,0.0,NaN,0,0,1,0,3,6,1,0,90.000000,100.000000,10.000000,3.909825
11,11,NaN,NaN,NaN,NaN,NaN,46.363533,0,0,0,0,3,6,1,0,90.000000,100.000000,10.000000,3.909825
12,12,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,3,7,1,0,90.909091,100.000000,9.090909,3.909825
13,13,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,3,8,1,0,91.666667,100.000000,8.333333,3.909825
14,14,"[('1', 0.79029209993314)]",1.0,0.790292,1.0,7.0,NaN,1,0,0,0,4,8,1,0,92.307692,100.000000,7.692308,3.285918
15,15,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,4,9,1,0,92.857143,100.000000,7.142857,3.285918
16,16,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,4,10,1,0,93.333333,100.000000,6.666667,3.285918
17,17,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,4,11,1,0,93.750000,100.000000,6.250000,3.285918
18,18,"[('1', 0.6049618000397459)]",1.0,0.604962,1.0,7.0,NaN,1,0,0,0,5,11,1,0,94.117647,100.000000,5.882353,2.839092
19,19,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,5,12,1,0,94.444444,100.000000,5.555556,2.839092
20,20,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,5,13,1,0,94.736842,100.000000,5.263158,2.839092
21,21,"[('1', 10.02883959992323)]",1.0,10.028840,1.0,7.0,NaN,1,0,0,0,6,13,1,0,95.000000,100.000000,5.000000,3.866199
22,22,NaN,NaN,NaN,NaN,NaN,94.592743,0,0,0,0,6,13,1,0,95.000000,100.000000,5.000000,3.866199
23,23,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,6,14,1,0,95.238095,100.000000,4.761905,3.866199
24,24,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,6,15,1,0,95.454545,100.000000,4.545455,3.866199
25,25,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,6,16,1,0,95.652174,100.000000,4.347826,3.866199
26,26,"[('1', 0.6743261999217793)]",1.0,0.674326,1.0,7.0,NaN,1,0,0,0,7,16,1,0,95.833333,100.000000,4.166667,3.467215
27,27,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,7,17,1,0,96.000000,100.000000,4.000000,3.467215
28,28,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,7,18,1,0,96.153846,100.000000,3.846154,3.467215
29,29,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,7,19,1,0,96.296296,100.000000,3.703704,3.467215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,168,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,37,106,2,8,93.464052,82.222222,1.307190,1.421840
169,169,NaN,NaN,NaN,1.0,7.0,NaN,0,0,0,1,37,106,2,9,92.857143,80.434783,1.298701,1.421840
170,170,"[('1', 0.47131600009743124)]",1.0,0.471316,1.0,7.0,NaN,1,0,0,0,38,106,2,9,92.903226,80.851064,1.290323,1.398077
171,171,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,38,107,2,9,92.948718,80.851064,1.282051,1.398077
172,172,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,38,108,2,9,92.993631,80.851064,1.273885,1.398077
173,173,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,38,109,2,9,93.037975,80.851064,1.265823,1.398077
174,174,"[('1', 0.3879048000089824)]",1.0,0.387905,1.0,7.0,NaN,1,0,0,0,39,109,2,9,93.081761,81.250000,1.257862,1.373438
175,175,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,110,2,9,93.125000,81.250000,1.250000,1.373438
176,176,NaN,NaN,NaN,NaN,NaN,795.368431,0,0,0,0,39,110,2,9,93.125000,81.250000,1.250000,1.373438
177,177,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,111,2,9,93.167702,81.250000,1.242236,1.373438
178,178,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,112,2,9,93.209877,81.250000,1.234568,1.373438
179,179,NaN,NaN,NaN,1.0,7.0,NaN,0,0,0,1,39,112,2,10,92.638037,79.591837,1.226994,1.373438
180,180,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,113,2,10,92.682927,79.591837,1.219512,1.373438
181,181,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,114,2,10,92.727273,79.591837,1.212121,1.373438
182,182,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,115,2,10,92.771084,79.591837,1.204819,1.373438
183,183,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,116,2,10,92.814371,79.591837,1.197605,1.373438
184,184,"[('1', 0.5787306999554858)]",1.0,0.578731,1.0,7.0,NaN,1,0,0,0,40,116,2,10,92.857143,80.000000,1.190476,1.354517
185,185,"[('1', 1.188213099958375)]",1.0,1.188213,1.0,7.0,NaN,1,0,0,0,41,116,2,10,92.899408,80.392157,1.183432,1.350649
186,186,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,41,117,2,10,92.941176,80.392157,1.176471,1.350649
187,187,NaN,NaN,NaN,NaN,NaN,843.620533,0,0,0,0,41,117,2,10,92.941176,80.392157,1.176471,1.350649
188,188,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,41,118,2,10,92.982456,80.392157,1.169591,1.350649
189,189,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,41,119,2,10,93.023256,80.392157,1.162791,1.350649
190,190,"[('1', 0.5888627999229357)]",1.0,0.588863,1.0,7.0,NaN,1,0,0,0,42,119,2,10,93.063584,80.769231,1.156069,1.333336
191,191,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,42,120,2,10,93.103448,80.769231,1.149425,1.333336
192,192,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,42,121,2,10,93.142857,80.769231,1.142857,1.333336
193,193,"[('1', 0.5782230000477284)]",1.0,0.578223,1.0,7.0,NaN,1,0,0,0,43,121,2,10,93.181818,81.132075,1.136364,1.316555
194,194,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,43,122,2,10,93.220339,81.132075,1.129944,1.316555
195,195,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,43,123,2,10,93.258427,81.132075,1.123596,1.316555
196,196,"[('1', 0.5223766000708565)]",1.0,0.522377,1.0,7.0,NaN,1,0,0,0,44,123,2,10,93.296089,81.481481,1.117318,1.299291
197,197,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,44,124,2,10,93.333333,81.481481,1.111111,1.299291

In [7]:
data_ref.describe()

,trial,block_num,corr_resp,corr_resp_left,trial_dur,new_block
count,396.0000,396.000000,360.000000,360.000000,396.000000,396.000000
mean,198.5000,5.000000,0.300000,2.100000,2.121212,0.045455
std,114.4596,2.585255,0.458895,3.212268,3.240637,0.208562
min,1.0000,1.000000,0.000000,0.000000,0.500000,0.000000
25%,99.7500,3.000000,0.000000,0.000000,0.500000,0.000000
50%,198.5000,5.000000,0.000000,0.000000,1.500000,0.000000
75%,297.2500,7.000000,1.000000,7.000000,2.500000,0.000000
max,396.0000,9.000000,1.000000,7.000000,19.000000,1.000000

In [9]:
data_ref

,A_or_B,trial,block_num,trial_type,corr_resp,corr_resp_left,image_name,trial_dur,new_block
0,A,1,1,0,NaN,NaN,stimuli/0back_instr.jpg,3.0,1
1,NaN,2,1,fix,NaN,NaN,stimuli/fix.jpg,0.5,0
2,NaN,3,1,0,0.0,0.0,stimuli/7.jpg,0.5,0
3,NaN,4,1,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
4,NaN,5,1,0,1.0,7.0,stimuli/8.jpg,0.5,0
5,NaN,6,1,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
6,NaN,7,1,0,0.0,0.0,stimuli/4.jpg,0.5,0
7,NaN,8,1,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
8,NaN,9,1,0,0.0,0.0,stimuli/6.jpg,0.5,0
9,NaN,10,1,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
10,NaN,11,1,0,1.0,7.0,stimuli/8.jpg,0.5,0
11,NaN,12,1,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
12,NaN,13,1,0,0.0,0.0,stimuli/1.jpg,0.5,0
13,NaN,14,1,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
14,NaN,15,1,0,0.0,0.0,stimuli/5.jpg,0.5,0
15,NaN,16,1,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
16,NaN,17,1,0,1.0,7.0,stimuli/8.jpg,0.5,0
17,NaN,18,1,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
18,NaN,19,1,0,0.0,0.0,stimuli/3.jpg,0.5,0
19,NaN,20,1,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
20,NaN,21,1,0,0.0,0.0,stimuli/2.jpg,0.5,0
21,NaN,22,1,fix,0.0,0.0,stimuli/fix.jpg,15.0,0
22,NaN,23,2,1,NaN,NaN,stimuli/1back_instr.jpg,3.0,1
23,NaN,24,2,fix,NaN,NaN,stimuli/fix.jpg,0.5,0
24,NaN,25,2,1,0.0,0.0,stimuli/4_lower.jpg,0.5,0
25,NaN,26,2,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
26,NaN,27,2,1,0.0,0.0,stimuli/5_lower.jpg,0.5,0
27,NaN,28,2,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
28,NaN,29,2,1,1.0,7.0,stimuli/5_lower.jpg,0.5,0
29,NaN,30,2,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
...,...,...,...,...,...,...,...,...,...
366,NaN,367,8,1,0.0,0.0,stimuli/2.jpg,0.5,0
367,NaN,368,8,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
368,NaN,369,8,1,1.0,7.0,stimuli/2.jpg,0.5,0
369,NaN,370,8,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
370,NaN,371,8,1,1.0,7.0,stimuli/2.jpg,0.5,0
371,NaN,372,8,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
372,NaN,373,8,1,0.0,0.0,stimuli/6.jpg,0.5,0
373,NaN,374,8,fix,0.0,0.0,stimuli/fix.jpg,17.0,0
374,NaN,375,9,0,NaN,NaN,stimuli/0back_instr.jpg,3.0,1
375,NaN,376,9,fix,NaN,NaN,stimuli/fix.jpg,0.5,0
376,NaN,377,9,0,0.0,0.0,stimuli/2.jpg,0.5,0
377,NaN,378,9,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
378,NaN,379,9,0,0.0,0.0,stimuli/3.jpg,0.5,0
379,NaN,380,9,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
380,NaN,381,9,0,1.0,7.0,stimuli/8.jpg,0.5,0
381,NaN,382,9,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
382,NaN,383,9,0,0.0,0.0,stimuli/5.jpg,0.5,0
383,NaN,384,9,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
384,NaN,385,9,0,0.0,0.0,stimuli/1.jpg,0.5,0
385,NaN,386,9,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
386,NaN,387,9,0,1.0,7.0,stimuli/8.jpg,0.5,0
387,NaN,388,9,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
388,NaN,389,9,0,0.0,0.0,stimuli/6.jpg,0.5,0
389,NaN,390,9,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
390,NaN,391,9,0,0.0,0.0,stimuli/4.jpg,0.5,0
391,NaN,392,9,fix,0.0,0.0,stimuli/fix.jpg,2.5,0
392,NaN,393,9,0,1.0,7.0,stimuli/8.jpg,0.5,0
393,NaN,394,9,fix,1.0,7.0,stimuli/fix.jpg,2.5,0
394,NaN,395,9,0,0.0,0.0,stimuli/7.jpg,0.5,0
395,NaN,396,9,fix,0.0,0.0,stimuli/fix.jpg,5.0,0

In [44]:
data_main

,main_trial_id,subj_key_resp,subj_key_resp_first,rxn_time,corr_resp,corr_resp_left,running_time,hits,corr_skips,false_alarm,misses,total_hits,total_corr_skips,total_false_alarm,total_misses,overall_accuracy,hit_accuracy,false_alarm_rate,avg_rxn_time
0,0,NaN,NaN,NaN,NaN,NaN,0.207622,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,0,1,0,0,100.000000,NaN,0.000000,NaN
2,2,"[('1', 0.47146260004956275)]",1.0,0.471463,1.0,7.0,NaN,1,0,0,0,1,1,0,0,100.000000,100.000000,0.000000,0.471463
3,3,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,1,2,0,0,100.000000,100.000000,0.000000,0.471463
4,4,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,1,3,0,0,100.000000,100.000000,0.000000,0.471463
5,5,"[('1', 0.42485980002675205)]",1.0,0.424860,1.0,7.0,NaN,1,0,0,0,2,3,0,0,100.000000,100.000000,0.000000,0.448161
6,6,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,2,4,0,0,100.000000,100.000000,0.000000,0.448161
7,7,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,2,5,0,0,100.000000,100.000000,0.000000,0.448161
8,8,"[('1', 0.4552331999875605)]",1.0,0.455233,1.0,7.0,NaN,1,0,0,0,3,5,0,0,100.000000,100.000000,0.000000,0.450519
9,9,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,3,6,0,0,100.000000,100.000000,0.000000,0.450519
10,10,"[('1', 14.287743899971247)]",1.0,14.287744,0.0,0.0,NaN,0,0,1,0,3,6,1,0,90.000000,100.000000,10.000000,3.909825
11,11,NaN,NaN,NaN,NaN,NaN,46.363533,0,0,0,0,3,6,1,0,90.000000,100.000000,10.000000,3.909825
12,12,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,3,7,1,0,90.909091,100.000000,9.090909,3.909825
13,13,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,3,8,1,0,91.666667,100.000000,8.333333,3.909825
14,14,"[('1', 0.79029209993314)]",1.0,0.790292,1.0,7.0,NaN,1,0,0,0,4,8,1,0,92.307692,100.000000,7.692308,3.285918
15,15,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,4,9,1,0,92.857143,100.000000,7.142857,3.285918
16,16,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,4,10,1,0,93.333333,100.000000,6.666667,3.285918
17,17,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,4,11,1,0,93.750000,100.000000,6.250000,3.285918
18,18,"[('1', 0.6049618000397459)]",1.0,0.604962,1.0,7.0,NaN,1,0,0,0,5,11,1,0,94.117647,100.000000,5.882353,2.839092
19,19,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,5,12,1,0,94.444444,100.000000,5.555556,2.839092
20,20,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,5,13,1,0,94.736842,100.000000,5.263158,2.839092
21,21,"[('1', 10.02883959992323)]",1.0,10.028840,1.0,7.0,NaN,1,0,0,0,6,13,1,0,95.000000,100.000000,5.000000,3.866199
22,22,NaN,NaN,NaN,NaN,NaN,94.592743,0,0,0,0,6,13,1,0,95.000000,100.000000,5.000000,3.866199
23,23,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,6,14,1,0,95.238095,100.000000,4.761905,3.866199
24,24,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,6,15,1,0,95.454545,100.000000,4.545455,3.866199
25,25,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,6,16,1,0,95.652174,100.000000,4.347826,3.866199
26,26,"[('1', 0.6743261999217793)]",1.0,0.674326,1.0,7.0,NaN,1,0,0,0,7,16,1,0,95.833333,100.000000,4.166667,3.467215
27,27,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,7,17,1,0,96.000000,100.000000,4.000000,3.467215
28,28,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,7,18,1,0,96.153846,100.000000,3.846154,3.467215
29,29,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,7,19,1,0,96.296296,100.000000,3.703704,3.467215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,168,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,37,106,2,8,93.464052,82.222222,1.307190,1.421840
169,169,NaN,NaN,NaN,1.0,7.0,NaN,0,0,0,1,37,106,2,9,92.857143,80.434783,1.298701,1.421840
170,170,"[('1', 0.47131600009743124)]",1.0,0.471316,1.0,7.0,NaN,1,0,0,0,38,106,2,9,92.903226,80.851064,1.290323,1.398077
171,171,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,38,107,2,9,92.948718,80.851064,1.282051,1.398077
172,172,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,38,108,2,9,92.993631,80.851064,1.273885,1.398077
173,173,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,38,109,2,9,93.037975,80.851064,1.265823,1.398077
174,174,"[('1', 0.3879048000089824)]",1.0,0.387905,1.0,7.0,NaN,1,0,0,0,39,109,2,9,93.081761,81.250000,1.257862,1.373438
175,175,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,110,2,9,93.125000,81.250000,1.250000,1.373438
176,176,NaN,NaN,NaN,NaN,NaN,795.368431,0,0,0,0,39,110,2,9,93.125000,81.250000,1.250000,1.373438
177,177,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,111,2,9,93.167702,81.250000,1.242236,1.373438
178,178,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,112,2,9,93.209877,81.250000,1.234568,1.373438
179,179,NaN,NaN,NaN,1.0,7.0,NaN,0,0,0,1,39,112,2,10,92.638037,79.591837,1.226994,1.373438
180,180,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,113,2,10,92.682927,79.591837,1.219512,1.373438
181,181,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,114,2,10,92.727273,79.591837,1.212121,1.373438
182,182,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,115,2,10,92.771084,79.591837,1.204819,1.373438
183,183,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,39,116,2,10,92.814371,79.591837,1.197605,1.373438
184,184,"[('1', 0.5787306999554858)]",1.0,0.578731,1.0,7.0,NaN,1,0,0,0,40,116,2,10,92.857143,80.000000,1.190476,1.354517
185,185,"[('1', 1.188213099958375)]",1.0,1.188213,1.0,7.0,NaN,1,0,0,0,41,116,2,10,92.899408,80.392157,1.183432,1.350649
186,186,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,41,117,2,10,92.941176,80.392157,1.176471,1.350649
187,187,NaN,NaN,NaN,NaN,NaN,843.620533,0,0,0,0,41,117,2,10,92.941176,80.392157,1.176471,1.350649
188,188,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,41,118,2,10,92.982456,80.392157,1.169591,1.350649
189,189,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,41,119,2,10,93.023256,80.392157,1.162791,1.350649
190,190,"[('1', 0.5888627999229357)]",1.0,0.588863,1.0,7.0,NaN,1,0,0,0,42,119,2,10,93.063584,80.769231,1.156069,1.333336
191,191,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,42,120,2,10,93.103448,80.769231,1.149425,1.333336
192,192,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,42,121,2,10,93.142857,80.769231,1.142857,1.333336
193,193,"[('1', 0.5782230000477284)]",1.0,0.578223,1.0,7.0,NaN,1,0,0,0,43,121,2,10,93.181818,81.132075,1.136364,1.316555
194,194,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,43,122,2,10,93.220339,81.132075,1.129944,1.316555
195,195,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,43,123,2,10,93.258427,81.132075,1.123596,1.316555
196,196,"[('1', 0.5223766000708565)]",1.0,0.522377,1.0,7.0,NaN,1,0,0,0,44,123,2,10,93.296089,81.481481,1.117318,1.299291
197,197,NaN,NaN,NaN,0.0,0.0,NaN,0,1,0,0,44,124,2,10,93.333333,81.481481,1.111111,1.299291

In [63]:
data_merge['trial_type'].astype(str).astype(int)
#data_merge

ValueError: invalid literal for int() with base 10: 'fix'

# End-to-end

In [66]:
# Ver. 1
data_main = pd.read_csv('./data/AA06LC00_Nback_2021_Jun_09_1034.csv')
data_ref  = pd.read_csv('./data/nback_AB.csv')

# Sanity check
assert 2*len(data_main) == len(data_ref)

# Create a new data column 'main_trial_id' based on the'trial' column.
# The 'main_trial_id' column will be used to map (joining two tables) data between main.csv and ref.csv
#data_ref['main_trial_id'] = np.floor((data_ref['trial']-1)/2).values.astype(np.int)

# Rename unnamed column of main.csv.
#data_main.rename(columns={ data_main.columns[0]: "main_trial_id" }, inplace = True)

#data_merge = pd.merge(data_main, data_ref, on="main_trial_id")

#data_merge[data_merge['trial_type']==0]

In [128]:
# Ver. 2
data_main = pd.read_csv('./data/AA06LC00_Nback_2021_Jun_09_1034.csv')
data_ref  = pd.read_csv('./data/nback_AB.csv')


# Sanity check
assert 2*len(data_main) == len(data_ref)

# Remove items having 'fix' trial_type in ref.csv
data_ref = data_ref[data_ref['trial_type'].astype(str) != 'fix']
# Create a new data column 'main_trial_id' based on the'trial' column.
# The 'main_trial_id' column will be used to map (joining two tables) data between main.csv and ref.csv
data_ref['main_trial_id'] = np.floor(data_ref['trial']/2).values.astype(np.int)

# Rename unnamed column of main.csv.
data_main.rename(columns={ data_main.columns[0]: "main_trial_id" }, inplace = True)

# Join main.csv and ref.csv
data_merge = pd.merge(data_main, data_ref, on="main_trial_id")
# Drop items showing instr.jpg
data_merge = data_merge[~data_merge['image_name'].str.endswith("back_instr.jpg")]

'''
# Per condition (load size)
data_load_0 = data_merge[data_merge['trial_type'].astype(int) == 0]
data_load_1 = data_merge[data_merge['trial_type'].astype(int) == 1]
data_load_2 = data_merge[data_merge['trial_type'].astype(int) == 2]

# Get response time
data_load_0_rxn_time = data_load_0['rxn_time']
data_load_1_rxn_time = data_load_1['rxn_time']
data_load_2_rxn_time = data_load_2['rxn_time']

# drop NaNs
data_load_0_rxn_time_clean = data_load_0_rxn_time.dropna()
data_load_1_rxn_time_clean = data_load_1_rxn_time.dropna()
data_load_2_rxn_time_clean = data_load_2_rxn_time.dropna()
'''

# Goal 1:  average response time per load size (0, 1, 2)
data_merge.groupby('trial_type').mean()
# Goal 2: average response time per stimulus
data_merge.groupby('image_name').mean()

,main_trial_id,subj_key_resp_first,rxn_time,corr_resp_x,corr_resp_left_x,running_time,hits,corr_skips,false_alarm,misses,...,overall_accuracy,hit_accuracy,false_alarm_rate,avg_rxn_time,trial,block_num,corr_resp_y,corr_resp_left_y,trial_dur,new_block
image_name,,,,,,,,,,,,,,,,,,,,,
stimuli/1.jpg,114.733333,1.0,0.435247,0.333333,2.333333,NaN,0.200000,0.666667,0.000000,0.133333,...,94.532033,88.439770,2.010874,1.694226,230.466667,5.533333,0.333333,2.333333,0.5,0.0
stimuli/1_lower.jpg,78.600000,1.0,4.895641,0.300000,2.100000,NaN,0.300000,0.600000,0.100000,0.000000,...,93.895165,91.760111,3.649466,2.465800,158.200000,4.000000,0.300000,2.100000,0.5,0.0
stimuli/2.jpg,122.454545,1.0,5.351563,0.181818,1.272727,NaN,0.181818,0.727273,0.090909,0.000000,...,93.573500,87.653581,2.744923,1.919588,245.909091,5.818182,0.181818,1.272727,0.5,0.0
stimuli/2_lower.jpg,67.800000,1.0,0.678273,0.400000,2.800000,NaN,0.400000,0.600000,0.000000,0.000000,...,93.724410,92.820748,4.134145,2.536520,136.600000,4.100000,0.400000,2.800000,0.5,0.0
stimuli/3.jpg,115.285714,1.0,0.647302,0.214286,1.500000,NaN,0.142857,0.785714,0.000000,0.071429,...,94.562762,88.536109,2.020576,1.683593,231.571429,5.285714,0.214286,1.500000,0.5,0.0
stimuli/3_lower.jpg,85.857143,1.0,0.561814,0.214286,1.500000,NaN,0.142857,0.785714,0.000000,0.071429,...,94.326071,91.626488,3.175251,2.391513,172.714286,5.000000,0.214286,1.500000,0.5,0.0
stimuli/4.jpg,104.900000,NaN,NaN,0.100000,0.700000,NaN,0.000000,0.900000,0.000000,0.100000,...,94.822929,89.512160,2.030861,1.681839,210.800000,4.600000,0.100000,0.700000,0.5,0.0
stimuli/4_lower.jpg,90.900000,1.0,0.573228,0.300000,2.100000,NaN,0.300000,0.700000,0.000000,0.000000,...,94.377303,91.919144,3.216496,2.358567,182.800000,5.200000,0.300000,2.100000,0.5,0.0
stimuli/5.jpg,103.545455,1.0,2.688626,0.181818,1.272727,NaN,0.090909,0.818182,0.000000,0.090909,...,94.814189,89.815806,2.142545,1.739981,208.090909,5.000000,0.181818,1.272727,0.5,0.0
stimuli/5_lower.jpg,88.454545,1.0,0.790292,0.363636,2.545455,NaN,0.090909,0.636364,0.000000,0.272727,...,94.193469,91.632466,3.309785,2.321934,177.909091,4.454545,0.363636,2.545455,0.5,0.0
stimuli/6.jpg,115.923077,1.0,0.540908,0.153846,1.076923,NaN,0.153846,0.846154,0.000000,0.000000,...,94.538852,88.173333,1.922906,1.657300,232.846154,5.461538,0.153846,1.076923,0.5,0.0
stimuli/6_lower.jpg,83.285714,NaN,NaN,0.000000,0.000000,NaN,0.000000,1.000000,0.000000,0.000000,...,93.590815,90.345072,3.552844,2.538832,167.571429,5.571429,0.000000,0.000000,0.5,0.0
stimuli/7.jpg,105.333333,1.0,0.750403,0.250000,1.750000,NaN,0.166667,0.750000,0.000000,0.083333,...,94.922877,88.934240,2.038305,1.804470,211.666667,4.833333,0.250000,1.750000,0.5,0.0
stimuli/7_lower.jpg,86.333333,1.0,0.445128,0.166667,1.166667,NaN,0.166667,0.833333,0.000000,0.000000,...,94.917327,93.358918,3.132970,2.124054,173.666667,5.333333,0.166667,1.166667,0.5,0.0
stimuli/8.jpg,97.071429,1.0,0.527806,0.857143,6.000000,NaN,0.857143,0.142857,0.000000,0.000000,...,95.228283,90.491273,1.877550,1.526208,195.142857,4.214286,0.857143,6.000000,0.5,0.0
stimuli/8_lower.jpg,97.583333,1.0,0.522172,0.500000,3.500000,NaN,0.500000,0.500000,0.000000,0.000000,...,94.594445,91.061118,2.727693,2.065978,196.166667,5.583333,0.500000,3.500000,0.5,0.0

# Goal 1:  average response time per load size (0, 1, 2)

# Goal 2: average response time per stimulus